export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const GET_POKEMONS_TYPES = 'GET_POKEMONS_TYPES';
export const ORDER_POKEMONS_BY_NAME = 'ORDER_POKEMONS_BY_NAME';
export const FILTER_BY_PERSONALIZATION = 'FILTER_BY_PERSONALIZATION';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';